### PR TITLE
Add support for `@container` queries by updating the CSS language service

### LINKED ISSUE #14: Support container queries
Currently this code isn't understood

```css
container-type: inline-size;  // <- warning, "Unknown property: 'container-type'ts-styled-plugin(9999)"

.someChildren {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
};

@container (max-width: 10rem) { // <- error, "} expected ts-styled-plugin(9999)"
  .someChildren {
    flex-direction: column;
  }
}
```

### PR DESCRIPTION
**Pull request by marvinroger**
Closes #14 

This PR updates the CSS language service in order to support `@container` queries.

C.f. https://github.com/microsoft/vscode-css-languageservice/pull/365 and https://github.com/microsoft/vscode-css-languageservice/pull/371

The PR is ready to be published to npm 😉 

I'll make a followup PR to https://github.com/styled-components/vscode-styled-components once published

### CODE REVIEW

**Comment by marvinroger** [comment]
Thanks @jasonwilliams, just fixed the lockfile

**Comment by jasonwilliams** [comment]
oh dear, so many tests fail.
Not your fault, they fail even on master, I guess so many things have moved around since this was last built

**Comment by jasonwilliams** [comment]
Ok, no biggie, the e2e typescript version is just outdated compared to the main plugin typescript version. 
Ill merge this and update them both, then figures crossed tests pass again

**Comment by phuctm97** [comment]
For some reasons container query still doesn't work 🥹

**Comment by kitajchuk** [comment]
Also still not working for me as well.

**Pull request merged**
