### PR TITLE
update and fork

### PR DESCRIPTION
**Pull request by jasonwilliams**
- hwb(), var() and calc() added to the css language server. This raises the completions body length to 160 in tests
- Update dependencies

### CODE REVIEW

**Comment by karlhorky** [comment]
So since these updates were released in `styled-components.vscode-styled-components@1.7.6`, I tested them out, to see if it would get rid of this `aspect-ratio` warning from the issue below:

- https://github.com/microsoft/vscode-css-languageservice/pull/317

203062667-df167413-8d1d-4741-8bc2-c6c0ccd89ce8

I first tried out my installed version `styled-components.vscode-styled-components@1.7.5` with my new version of VS Code (1.74.0)... and... actually the error was already gone 🤔😳

Screenshot 2022-12-09 at 18 06 40

Indeed, it also works with `styled-components.vscode-styled-components@1.7.6`:

Screenshot 2022-12-09 at 18 07 26

---

So maybe somehow the updates of dependencies in `vscode-css-languageservice@6.2.1` already fixed it? (with the new release of VS Code 1.74.0 maybe?

- https://github.com/microsoft/vscode-css-languageservice/pull/319

**Comment by karlhorky** [comment]
Just ran into a different problem just now - [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) doesn't appear to work, in either the normal `styled-components.vscode-styled-components@1.7.5` Release version or the `styled-components.vscode-styled-components@1.7.6` Pre-Release version (see below).

Maybe the property is too new?

The error message is "Unknown property: 'accent-color".

Screenshot 2022-12-14 at 16 39 17

Screenshot 2022-12-14 at 16 38 50

**Comment by jasonwilliams** [comment]
yeah CSS properties aren't handled here but maybe you can help me find out a bit more how this chain works.
My understanding is it was added already: https://github.com/microsoft/vscode-custom-data/pull/33

but it hasn't made its way down to here, so maybe there's an issue somewhere.
we use https://github.com/microsoft/vscode-css-languageservice which pulls from https://github.com/microsoft/vscode-custom-data/tree/main/web-data and I can see it in there: https://github.com/microsoft/vscode-custom-data/blob/main/web-data/data/browsers.css-data.json#L19798

**Comment by karlhorky** [comment]
Interesting, with VS Code 1.77.0 and `styled-components.vscode-styled-components@1.7.5`, the `aspect-ratio` warnings don't show up anymore.

But also, no warnings about invalid properties are showing up 😬 , so maybe there's something wrong here generally:

Screenshot 2023-04-05 at 09 42 06

**Comment by jasonwilliams** [comment]
@karlhorky see https://github.com/styled-components/vscode-styled-components/issues/387#issuecomment-1493055728

you should try vs 1.7.7 (you’re using 1.7.5)

**Comment by karlhorky** [comment]
Yeah, I am on the stable version. I will wait until the new versions are no longer marked as pre-release to upgrade (as many users will)

**Comment by karlhorky** [comment]
But yes, the 1.7.7 prerelease does resolve the issue (see below). Downgrading again to stable.

Screenshot 2023-04-05 at 10 24 34

**Comment by nyxb** [comment]
i have this problem: 
image

**Comment by nyxb** [comment]
yeah but it has no effect.

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "allowImportingTsExtensions": true,
    "strictNullChecks": true,
    //  "noImplicitAny": false,
    "plugins": [
      {
        "name": "next"
      },
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": [
            "-webkit-background-clip",
            "vector-effect"
          ]
        }
      }
    ],
    "paths": {
      "@components/*": ["./src/components/*"],
      "@hooks/*": ["./src/hooks/*"],
      "@constants": ["./src/constants"],
      "@helpers/*": ["./src/helpers/*"],
      "@utils": ["./src/utils"],
      "@lib/*": ["./src/lib/*"],
      "@types": ["./types"],
      "@layouts/*": ["./src/layouts/*"],
      "@content": ["./src/content"],
      "@server/*": ["./src/server/*"],
      "@post-helpers/*": ["./src/post-helpers/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "types/**/*.d.ts", "src/helpers/mdx-components.helpers.js", "src/helpers/mdx-components.helpers.js", "src/components/Playground/Toolbar/FormatButton.js"],
  "exclude": ["node_modules"]
}
```

**Pull request merged**
